apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-boilerplate
  namespace: minikube
  labels:
    app: fe-boilerplate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-boilerplate
  template:
    metadata:
      labels:
        app: fe-boilerplate
    spec:
      containers:
        - name: fe-boilerplate
          image: matrix009/fe-boilerplate:v1.0.8
          ports:
            - containerPort: 80
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: fe-boilerplate
  namespace: minikube
  labels:
    app: fe-boilerplate
spec:
  type: NodePort
  selector:
    app: fe-boilerplate
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081

